# Generated by Django 4.2.20 on 2025-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eyewear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("brand", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("frame_material", models.CharField(max_length=100)),
                ("lens_material", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="eyewear_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"verbose_name": "Glasses", "ordering": ["-created_at"],},
        ),
    ]
